In [1]:
import pandas as pd

# Create filepaths for importing data
file_pathgg = "Comments/gigi_final.csv"
file_pathgg2 = "Comments/gigi2_final.csv"
file_pathm = "Comments/matilda_final.csv"
file_pathm2 = "Comments/matilda2_final.csv"

In [2]:
# Read gigi, gigi2, matilda, and matilda2 into dataframes
gg_df = pd.read_csv(file_pathgg)
gg_df.head()

,Unnamed: 0,Comments,Comment ID,Reply Count,Like Count,Updated At,Viewer Rating
0,0,So much make up!!! You are a natural Beauty so...,Ugw7WK5y_J606VRTvAp4AaABAg,0,0,2022-05-20T05:48:06Z,none
1,1,That sounds so scary. Sorry there is so much B...,UgygbjwBdXrZGu5YpsR4AaABAg,0,0,2022-04-30T10:59:24Z,none
2,2,Good thing you didn‚Äôt go through with it Sir ! üëç,Ugz7fes5DPfr97rd6pd4AaABAg,0,0,2022-04-22T22:10:33Z,none
3,3,Live how you want. Cutting yourself is just n...,UgwRUG3pY3b3n2zY7KB4AaABAg,0,0,2022-04-21T04:36:39Z,none
4,4,Watching this in 2022 *she said welcome to 202...,UgwveeN8c_bygkGmOfd4AaABAg,0,1,2022-03-20T21:35:02Z,none

In [3]:
gg2_df = pd.read_csv(file_pathgg2)
gg2_df.head()

,Unnamed: 0,Comments,Comment ID,Reply Count,Like Count,Updated At,Viewer Rating
0,0,Sooo.... you are saying ...nothing new here. ...,UgxiL7p2wONqUB3Nath4AaABAg,0,0,2022-05-11T13:03:08Z,none
1,1,It‚Äôs so odd to me how people have to label thi...,UgxQiEdEGYCqI_CvoId4AaABAg,0,0,2022-05-06T16:09:34Z,none
2,2,They did their best with all the technology We...,Ugwyvn0XDDjpGlabPll4AaABAg,0,1,2022-04-27T23:15:32Z,none
3,3,JLove purfume by Jennifer Lopez Megan fox I lo...,UgzYHbdmZ83p_7yyBnF4AaABAg,0,0,2022-04-26T22:14:25Z,none
4,4,USA : don't put labels on people ! don't be ra...,Ugx4ceVWEboUqJGQDfF4AaABAg,0,0,2022-04-25T11:01:41Z,none

In [4]:
m_df = pd.read_csv(file_pathm)
m_df.head()

,Unnamed: 0,Comments,Comment ID,Reply Count,Like Count,Updated At,Viewer Rating
0,0,My Instagram: https://www.instagram.com/mathil...,Ugwg_TJvQOB5tMk6fnV4AaABAg,16,106,2020-11-03T17:32:00Z,none
1,1,I‚Äôm jealous. As a REAL WOMAN *unlike you* I su...,UgykaIZTttVeVaJpvzx4AaABAg,1,0,2022-05-17T05:47:48Z,none
2,2,I don‚Äôt want to get shorter but I want all the...,UgzRUjYDrUmzaa9Ydm94AaABAg,0,0,2022-05-15T20:48:13Z,none
3,3,Bs,UgxXCkmLAvtDudQL1bF4AaABAg,0,0,2022-05-11T21:22:47Z,none
4,4,"What's up dude, how they hanging?",UgwP-n5vyVEYvrueJll4AaABAg,2,0,2022-05-09T23:41:45Z,none

In [5]:
m2_df = pd.read_csv(file_pathm2)
m2_df.head()

,Unnamed: 0,Comments,Comment ID,Reply Count,Like Count,Updated At,Viewer Rating
0,0,You're lucky that u born in Sweden and also u ...,UgzutqVVZqPDmbpMLEp4AaABAg,0,0,2022-04-27T13:19:53Z,none
1,1,You do what makes you happy,Ugx-ScZ3kZz4JXi12vd4AaABAg,0,0,2022-04-16T19:29:40Z,none
2,2,Omgggg I‚Äôm so happy for youuu‚ù§Ô∏è‚ù§Ô∏è‚ù§Ô∏è‚ù§Ô∏è,Ugy8hLbP2zgXHoMpKwx4AaABAg,0,0,2022-04-02T18:22:08Z,none
3,3,All of you who hate on her shows just how this...,UgyNtPIeNh-z8MRzBOx4AaABAg,0,0,2022-03-27T05:58:04Z,none
4,4,Thank you and Respect to you for being Honest....,UgzBhk1b5jmeSUDWZMF4AaABAg,0,0,2022-03-18T16:13:55Z,none

In [6]:
# Drop unnamed column
gg_df.drop(gg_df.filter(regex="Unname"), axis=1, inplace=True)
gg_df

,Comments,Comment ID,Reply Count,Like Count,Updated At,Viewer Rating
0,So much make up!!! You are a natural Beauty so...,Ugw7WK5y_J606VRTvAp4AaABAg,0,0,2022-05-20T05:48:06Z,none
1,That sounds so scary. Sorry there is so much B...,UgygbjwBdXrZGu5YpsR4AaABAg,0,0,2022-04-30T10:59:24Z,none
2,Good thing you didn‚Äôt go through with it Sir ! üëç,Ugz7fes5DPfr97rd6pd4AaABAg,0,0,2022-04-22T22:10:33Z,none
3,Live how you want. Cutting yourself is just n...,UgwRUG3pY3b3n2zY7KB4AaABAg,0,0,2022-04-21T04:36:39Z,none
4,Watching this in 2022 *she said welcome to 202...,UgwveeN8c_bygkGmOfd4AaABAg,0,1,2022-03-20T21:35:02Z,none
...,...,...,...,...,...,...
1446,First omg,UgxrnRN9GDrdyyDljrh4AaABAg,0,0,2019-03-05T00:08:31Z,none
1447,Love you!!,UgwpliRHUPcWSVmdyy14AaABAg,0,2,2019-03-05T00:08:31Z,none
1448,First,Ugwl2iDKEq6OzxZZoNV4AaABAg,0,0,2019-03-05T00:08:30Z,none
1449,1st like!,UgxUuWTujLfgNh42FnF4AaABAg,0,0,2019-03-05T00:08:30Z,none
1450,Im here gurlll!!!! Love you,UgyKv42_7zxzCIkPWRh4AaABAg,0,0,2019-03-05T00:08:28Z,none

In [7]:
gg2_df.drop(gg2_df.filter(regex="Unname"), axis=1, inplace=True)
gg2_df

,Comments,Comment ID,Reply Count,Like Count,Updated At,Viewer Rating
0,Sooo.... you are saying ...nothing new here. ...,UgxiL7p2wONqUB3Nath4AaABAg,0,0,2022-05-11T13:03:08Z,none
1,It‚Äôs so odd to me how people have to label thi...,UgxQiEdEGYCqI_CvoId4AaABAg,0,0,2022-05-06T16:09:34Z,none
2,They did their best with all the technology We...,Ugwyvn0XDDjpGlabPll4AaABAg,0,1,2022-04-27T23:15:32Z,none
3,JLove purfume by Jennifer Lopez Megan fox I lo...,UgzYHbdmZ83p_7yyBnF4AaABAg,0,0,2022-04-26T22:14:25Z,none
4,USA : don't put labels on people ! don't be ra...,Ugx4ceVWEboUqJGQDfF4AaABAg,0,0,2022-04-25T11:01:41Z,none
...,...,...,...,...,...,...
1300,First!,UgzpOdbR0PU9a3IgYEN4AaABAg,0,0,2021-04-09T17:39:46Z,none
1301,Go off queen,UgwP_UuQS5YiYDpgp7l4AaABAg,0,2,2021-04-09T17:39:45Z,none
1302,Claim your ‚Äúhere within an hour‚Äù ticket right ...,UgwAlBehv7CQrBAUVd14AaABAg,6,337,2021-04-09T17:39:43Z,none
1303,Omg whar,UgzImE1-tk53CXR6o1t4AaABAg,0,1,2021-04-09T17:39:41Z,none
1304,‚ÄúCongrats to everyone who is early and who fou...,UgwVVZUYpAG49BUJ1Pd4AaABAg,4,243,2021-04-09T17:39:39Z,none

In [8]:
m_df.drop(m_df.filter(regex="Unname"), axis=1, inplace=True)
m_df.head()

,Comments,Comment ID,Reply Count,Like Count,Updated At,Viewer Rating
0,My Instagram: https://www.instagram.com/mathil...,Ugwg_TJvQOB5tMk6fnV4AaABAg,16,106,2020-11-03T17:32:00Z,none
1,I‚Äôm jealous. As a REAL WOMAN *unlike you* I su...,UgykaIZTttVeVaJpvzx4AaABAg,1,0,2022-05-17T05:47:48Z,none
2,I don‚Äôt want to get shorter but I want all the...,UgzRUjYDrUmzaa9Ydm94AaABAg,0,0,2022-05-15T20:48:13Z,none
3,Bs,UgxXCkmLAvtDudQL1bF4AaABAg,0,0,2022-05-11T21:22:47Z,none
4,"What's up dude, how they hanging?",UgwP-n5vyVEYvrueJll4AaABAg,2,0,2022-05-09T23:41:45Z,none

In [9]:
m2_df.drop(m2_df.filter(regex="Unname"), axis=1, inplace=True)
m2_df.head()

,Comments,Comment ID,Reply Count,Like Count,Updated At,Viewer Rating
0,I just want to die every day I‚Äôm constantly su...,UgxHqgGvRKeNxL5bq-Z4AaABAg,0,0,2022-05-16T03:18:54Z,none
1,My friend recently came out as trans and I'm w...,Ugwub1JDGvy-NpWcv1R4AaABAg,0,0,2022-03-01T22:54:24Z,none
2,While I cannot relate to going through Dysphor...,UgxXxzPUjGwFpuCjmit4AaABAg,0,0,2022-02-10T21:31:07Z,none
3,My parents aren't letting me even change my na...,UgwghV-9Jf5zaQ8HFN54AaABAg,0,0,2022-02-02T13:19:29Z,none
4,Funny...even before I seriously considered tha...,Ugx20hOsS1ArBLu4WZ94AaABAg,0,1,2022-01-24T05:05:57Z,none

In [9]:
# Concatenate gg and gg2 
ggs_df = pd.concat([gg_df, gg2_df], axis=0)
ggs_df

,Comments,Comment ID,Reply Count,Like Count,Updated At,Viewer Rating
0,So much make up!!! You are a natural Beauty so...,Ugw7WK5y_J606VRTvAp4AaABAg,0,0,2022-05-20T05:48:06Z,none
1,That sounds so scary. Sorry there is so much B...,UgygbjwBdXrZGu5YpsR4AaABAg,0,0,2022-04-30T10:59:24Z,none
2,Good thing you didn‚Äôt go through with it Sir ! üëç,Ugz7fes5DPfr97rd6pd4AaABAg,0,0,2022-04-22T22:10:33Z,none
3,Live how you want. Cutting yourself is just n...,UgwRUG3pY3b3n2zY7KB4AaABAg,0,0,2022-04-21T04:36:39Z,none
4,Watching this in 2022 *she said welcome to 202...,UgwveeN8c_bygkGmOfd4AaABAg,0,1,2022-03-20T21:35:02Z,none
...,...,...,...,...,...,...
1300,First!,UgzpOdbR0PU9a3IgYEN4AaABAg,0,0,2021-04-09T17:39:46Z,none
1301,Go off queen,UgwP_UuQS5YiYDpgp7l4AaABAg,0,2,2021-04-09T17:39:45Z,none
1302,Claim your ‚Äúhere within an hour‚Äù ticket right ...,UgwAlBehv7CQrBAUVd14AaABAg,6,337,2021-04-09T17:39:43Z,none
1303,Omg whar,UgzImE1-tk53CXR6o1t4AaABAg,0,1,2021-04-09T17:39:41Z,none
1304,‚ÄúCongrats to everyone who is early and who fou...,UgwVVZUYpAG49BUJ1Pd4AaABAg,4,243,2021-04-09T17:39:39Z,none

In [10]:
# Concatenate m and m2
mat_df = pd.concat([m_df, m2_df], axis=0)
mat_df

,Comments,Comment ID,Reply Count,Like Count,Updated At,Viewer Rating,Unnamed: 0
0,My Instagram: https://www.instagram.com/mathil...,Ugwg_TJvQOB5tMk6fnV4AaABAg,16,106,2020-11-03T17:32:00Z,none,NaN
1,I‚Äôm jealous. As a REAL WOMAN *unlike you* I su...,UgykaIZTttVeVaJpvzx4AaABAg,1,0,2022-05-17T05:47:48Z,none,NaN
2,I don‚Äôt want to get shorter but I want all the...,UgzRUjYDrUmzaa9Ydm94AaABAg,0,0,2022-05-15T20:48:13Z,none,NaN
3,Bs,UgxXCkmLAvtDudQL1bF4AaABAg,0,0,2022-05-11T21:22:47Z,none,NaN
4,"What's up dude, how they hanging?",UgwP-n5vyVEYvrueJll4AaABAg,2,0,2022-05-09T23:41:45Z,none,NaN
...,...,...,...,...,...,...,...
173,Stay strong beautiful üíõ You are most beautiful...,UgwzOTT5SsmpWBRyEPJ4AaABAg,0,8,2020-01-06T14:50:46Z,none,173.0
174,üôåüèªüôåüèª‚ù§Ô∏è,Ugz5F4Qii9po4cLjwwZ4AaABAg,0,3,2020-01-06T14:39:08Z,none,174.0
175,‚ù§üíôüíöüíõüíúüíìüíïüíñ,Ugyki3yfUA5KCnE3_T14AaABAg,0,3,2020-01-06T14:27:43Z,none,175.0
176,You are so strong gurll. You are perfect‚ù§Ô∏è‚ù§Ô∏è,UgzSX4Fmc0WxiyEckJV4AaABAg,1,20,2020-01-06T14:22:09Z,none,176.0
177,Your still a perfekt person ‚ù§Ô∏è im so proud of ...,UgySaxspt2kq1Jk0zqF4AaABAg,0,21,2020-01-06T14:18:51Z,none,177.0

In [11]:
# Concatenate ggs and mat
mtf_df = pd.concat([ggs_df, mat_df], axis=0)
mtf_df

,Comments,Comment ID,Reply Count,Like Count,Updated At,Viewer Rating,Unnamed: 0
0,So much make up!!! You are a natural Beauty so...,Ugw7WK5y_J606VRTvAp4AaABAg,0,0,2022-05-20T05:48:06Z,none,NaN
1,That sounds so scary. Sorry there is so much B...,UgygbjwBdXrZGu5YpsR4AaABAg,0,0,2022-04-30T10:59:24Z,none,NaN
2,Good thing you didn‚Äôt go through with it Sir ! üëç,Ugz7fes5DPfr97rd6pd4AaABAg,0,0,2022-04-22T22:10:33Z,none,NaN
3,Live how you want. Cutting yourself is just n...,UgwRUG3pY3b3n2zY7KB4AaABAg,0,0,2022-04-21T04:36:39Z,none,NaN
4,Watching this in 2022 *she said welcome to 202...,UgwveeN8c_bygkGmOfd4AaABAg,0,1,2022-03-20T21:35:02Z,none,NaN
...,...,...,...,...,...,...,...
173,Stay strong beautiful üíõ You are most beautiful...,UgwzOTT5SsmpWBRyEPJ4AaABAg,0,8,2020-01-06T14:50:46Z,none,173.0
174,üôåüèªüôåüèª‚ù§Ô∏è,Ugz5F4Qii9po4cLjwwZ4AaABAg,0,3,2020-01-06T14:39:08Z,none,174.0
175,‚ù§üíôüíöüíõüíúüíìüíïüíñ,Ugyki3yfUA5KCnE3_T14AaABAg,0,3,2020-01-06T14:27:43Z,none,175.0
176,You are so strong gurll. You are perfect‚ù§Ô∏è‚ù§Ô∏è,UgzSX4Fmc0WxiyEckJV4AaABAg,1,20,2020-01-06T14:22:09Z,none,176.0
177,Your still a perfekt person ‚ù§Ô∏è im so proud of ...,UgySaxspt2kq1Jk0zqF4AaABAg,0,21,2020-01-06T14:18:51Z,none,177.0

In [12]:
# Drop viewer rating column
mtf_df.drop(columns="Viewer Rating", inplace=True)
mtf_df

,Comments,Comment ID,Reply Count,Like Count,Updated At,Unnamed: 0
0,So much make up!!! You are a natural Beauty so...,Ugw7WK5y_J606VRTvAp4AaABAg,0,0,2022-05-20T05:48:06Z,NaN
1,That sounds so scary. Sorry there is so much B...,UgygbjwBdXrZGu5YpsR4AaABAg,0,0,2022-04-30T10:59:24Z,NaN
2,Good thing you didn‚Äôt go through with it Sir ! üëç,Ugz7fes5DPfr97rd6pd4AaABAg,0,0,2022-04-22T22:10:33Z,NaN
3,Live how you want. Cutting yourself is just n...,UgwRUG3pY3b3n2zY7KB4AaABAg,0,0,2022-04-21T04:36:39Z,NaN
4,Watching this in 2022 *she said welcome to 202...,UgwveeN8c_bygkGmOfd4AaABAg,0,1,2022-03-20T21:35:02Z,NaN
...,...,...,...,...,...,...
173,Stay strong beautiful üíõ You are most beautiful...,UgwzOTT5SsmpWBRyEPJ4AaABAg,0,8,2020-01-06T14:50:46Z,173.0
174,üôåüèªüôåüèª‚ù§Ô∏è,Ugz5F4Qii9po4cLjwwZ4AaABAg,0,3,2020-01-06T14:39:08Z,174.0
175,‚ù§üíôüíöüíõüíúüíìüíïüíñ,Ugyki3yfUA5KCnE3_T14AaABAg,0,3,2020-01-06T14:27:43Z,175.0
176,You are so strong gurll. You are perfect‚ù§Ô∏è‚ù§Ô∏è,UgzSX4Fmc0WxiyEckJV4AaABAg,1,20,2020-01-06T14:22:09Z,176.0
177,Your still a perfekt person ‚ù§Ô∏è im so proud of ...,UgySaxspt2kq1Jk0zqF4AaABAg,0,21,2020-01-06T14:18:51Z,177.0

In [13]:
mtf_df.drop(mtf_df.filter(regex="Unname"), axis=1, inplace=True)
mtf_df

,Comments,Comment ID,Reply Count,Like Count,Updated At
0,So much make up!!! You are a natural Beauty so...,Ugw7WK5y_J606VRTvAp4AaABAg,0,0,2022-05-20T05:48:06Z
1,That sounds so scary. Sorry there is so much B...,UgygbjwBdXrZGu5YpsR4AaABAg,0,0,2022-04-30T10:59:24Z
2,Good thing you didn‚Äôt go through with it Sir ! üëç,Ugz7fes5DPfr97rd6pd4AaABAg,0,0,2022-04-22T22:10:33Z
3,Live how you want. Cutting yourself is just n...,UgwRUG3pY3b3n2zY7KB4AaABAg,0,0,2022-04-21T04:36:39Z
4,Watching this in 2022 *she said welcome to 202...,UgwveeN8c_bygkGmOfd4AaABAg,0,1,2022-03-20T21:35:02Z
...,...,...,...,...,...
173,Stay strong beautiful üíõ You are most beautiful...,UgwzOTT5SsmpWBRyEPJ4AaABAg,0,8,2020-01-06T14:50:46Z
174,üôåüèªüôåüèª‚ù§Ô∏è,Ugz5F4Qii9po4cLjwwZ4AaABAg,0,3,2020-01-06T14:39:08Z
175,‚ù§üíôüíöüíõüíúüíìüíïüíñ,Ugyki3yfUA5KCnE3_T14AaABAg,0,3,2020-01-06T14:27:43Z
176,You are so strong gurll. You are perfect‚ù§Ô∏è‚ù§Ô∏è,UgzSX4Fmc0WxiyEckJV4AaABAg,1,20,2020-01-06T14:22:09Z
177,Your still a perfekt person ‚ù§Ô∏è im so proud of ...,UgySaxspt2kq1Jk0zqF4AaABAg,0,21,2020-01-06T14:18:51Z

In [14]:
# Add new column with host gender identity (2=MaletoFemale)
mtf_df['Host Gender ID']=2
mtf_df

,Comments,Comment ID,Reply Count,Like Count,Updated At,Host Gender ID
0,So much make up!!! You are a natural Beauty so...,Ugw7WK5y_J606VRTvAp4AaABAg,0,0,2022-05-20T05:48:06Z,2
1,That sounds so scary. Sorry there is so much B...,UgygbjwBdXrZGu5YpsR4AaABAg,0,0,2022-04-30T10:59:24Z,2
2,Good thing you didn‚Äôt go through with it Sir ! üëç,Ugz7fes5DPfr97rd6pd4AaABAg,0,0,2022-04-22T22:10:33Z,2
3,Live how you want. Cutting yourself is just n...,UgwRUG3pY3b3n2zY7KB4AaABAg,0,0,2022-04-21T04:36:39Z,2
4,Watching this in 2022 *she said welcome to 202...,UgwveeN8c_bygkGmOfd4AaABAg,0,1,2022-03-20T21:35:02Z,2
...,...,...,...,...,...,...
173,Stay strong beautiful üíõ You are most beautiful...,UgwzOTT5SsmpWBRyEPJ4AaABAg,0,8,2020-01-06T14:50:46Z,2
174,üôåüèªüôåüèª‚ù§Ô∏è,Ugz5F4Qii9po4cLjwwZ4AaABAg,0,3,2020-01-06T14:39:08Z,2
175,‚ù§üíôüíöüíõüíúüíìüíïüíñ,Ugyki3yfUA5KCnE3_T14AaABAg,0,3,2020-01-06T14:27:43Z,2
176,You are so strong gurll. You are perfect‚ù§Ô∏è‚ù§Ô∏è,UgzSX4Fmc0WxiyEckJV4AaABAg,1,20,2020-01-06T14:22:09Z,2
177,Your still a perfekt person ‚ù§Ô∏è im so proud of ...,UgySaxspt2kq1Jk0zqF4AaABAg,0,21,2020-01-06T14:18:51Z,2

In [15]:
mtf_df.to_csv("mtf_comments.csv", index=False)