In [25]:
import pandas as pd

# Create filepaths for importing data
file_pathftm = "Comments/ftm_comments.csv"
file_pathmtf = "Comments/mtf_comments.csv"
file_pathnon = "Comments/nonbinary_comments.csv"

In [26]:
# Read ftm, mtf, nonbinary into dataframes
ftm_df = pd.read_csv(file_pathftm)
ftm_df.head()

,Comments,Comment ID,Reply Count,Like Count,Updated At,Host Gender ID
0,clicking on this video and seeing a bra ad,UgxBrS7R1KwdIarX7MR4AaABAg,0,0,2022-04-10T22:18:08Z,1
1,Great video I‚Äôm trans and I‚Äôm getting the flag...,UgwAU7kDdqLGnBTIICh4AaABAg,0,0,2022-04-07T02:59:00Z,1
2,Chase are you trans,UgxQB-5Q6WHtY9pDGEN4AaABAg,0,0,2022-03-21T20:30:23Z,1
3,I'm a school social worker using this for my o...,UgwxccL6DUDfB0jJcc94AaABAg,0,0,2022-01-26T15:07:42Z,1
4,Again with the ‚Äòflamboyant‚Äô? What does that me...,UgzfBCWxKXiPG2ZJUFd4AaABAg,0,0,2022-01-17T20:03:46Z,1

In [27]:
mtf_df = pd.read_csv(file_pathmtf)
mtf_df.head()

,Comments,Comment ID,Reply Count,Like Count,Updated At,Host Gender ID
0,So much make up!!! You are a natural Beauty so...,Ugw7WK5y_J606VRTvAp4AaABAg,0,0,2022-05-20T05:48:06Z,2
1,That sounds so scary. Sorry there is so much B...,UgygbjwBdXrZGu5YpsR4AaABAg,0,0,2022-04-30T10:59:24Z,2
2,Good thing you didn‚Äôt go through with it Sir ! üëç,Ugz7fes5DPfr97rd6pd4AaABAg,0,0,2022-04-22T22:10:33Z,2
3,Live how you want. Cutting yourself is just n...,UgwRUG3pY3b3n2zY7KB4AaABAg,0,0,2022-04-21T04:36:39Z,2
4,Watching this in 2022 *she said welcome to 202...,UgwveeN8c_bygkGmOfd4AaABAg,0,1,2022-03-20T21:35:02Z,2

In [29]:
nonbinary_df = pd.read_csv(file_pathnon)
nonbinary_df.head()

,Comments,Comment ID,Reply Count,Like Count,Updated At,Host Gender ID
0,Thank you!!!!!,Ugz_4WAMPzIE7ji2zaV4AaABAg,0,0,2022-05-24T04:40:07Z,3
1,‚ÄúSuper-feminine‚Äù lmfao,Ugwpssvx7JZmCwoFuV54AaABAg,0,0,2022-05-17T15:17:15Z,3
2,This actually helped clear a few things up for...,Ugz8SdClxFLdjyqmH9l4AaABAg,0,0,2022-04-17T15:12:17Z,3
3,so non binarys use they/them so they are ident...,Ugw0AM80jzCcL5IWqeV4AaABAg,0,1,2022-03-23T14:06:09Z,3
4,Oml thank you so much now I can call my non bi...,UgxDCr1Vrxikm7IUF5F4AaABAg,0,0,2022-03-02T14:48:05Z,3

In [30]:
# Concatenate ftm and mtf
trans_df = pd.concat([ftm_df, mtf_df], axis=0)
trans_df

,Comments,Comment ID,Reply Count,Like Count,Updated At,Host Gender ID
0,clicking on this video and seeing a bra ad,UgxBrS7R1KwdIarX7MR4AaABAg,0,0,2022-04-10T22:18:08Z,1
1,Great video I‚Äôm trans and I‚Äôm getting the flag...,UgwAU7kDdqLGnBTIICh4AaABAg,0,0,2022-04-07T02:59:00Z,1
2,Chase are you trans,UgxQB-5Q6WHtY9pDGEN4AaABAg,0,0,2022-03-21T20:30:23Z,1
3,I'm a school social worker using this for my o...,UgwxccL6DUDfB0jJcc94AaABAg,0,0,2022-01-26T15:07:42Z,1
4,Again with the ‚Äòflamboyant‚Äô? What does that me...,UgzfBCWxKXiPG2ZJUFd4AaABAg,0,0,2022-01-17T20:03:46Z,1
...,...,...,...,...,...,...
3849,Stay strong beautiful üíõ You are most beautiful...,UgwzOTT5SsmpWBRyEPJ4AaABAg,0,8,2020-01-06T14:50:46Z,2
3850,üôåüèªüôåüèª‚ù§Ô∏è,Ugz5F4Qii9po4cLjwwZ4AaABAg,0,3,2020-01-06T14:39:08Z,2
3851,‚ù§üíôüíöüíõüíúüíìüíïüíñ,Ugyki3yfUA5KCnE3_T14AaABAg,0,3,2020-01-06T14:27:43Z,2
3852,You are so strong gurll. You are perfect‚ù§Ô∏è‚ù§Ô∏è,UgzSX4Fmc0WxiyEckJV4AaABAg,1,20,2020-01-06T14:22:09Z,2
3853,Your still a perfekt person ‚ù§Ô∏è im so proud of ...,UgySaxspt2kq1Jk0zqF4AaABAg,0,21,2020-01-06T14:18:51Z,2

In [31]:
# Concatenate trans and nonbinary
transgender_df = pd.concat([trans_df, nonbinary_df], axis=0)
transgender_df

,Comments,Comment ID,Reply Count,Like Count,Updated At,Host Gender ID
0,clicking on this video and seeing a bra ad,UgxBrS7R1KwdIarX7MR4AaABAg,0,0,2022-04-10T22:18:08Z,1
1,Great video I‚Äôm trans and I‚Äôm getting the flag...,UgwAU7kDdqLGnBTIICh4AaABAg,0,0,2022-04-07T02:59:00Z,1
2,Chase are you trans,UgxQB-5Q6WHtY9pDGEN4AaABAg,0,0,2022-03-21T20:30:23Z,1
3,I'm a school social worker using this for my o...,UgwxccL6DUDfB0jJcc94AaABAg,0,0,2022-01-26T15:07:42Z,1
4,Again with the ‚Äòflamboyant‚Äô? What does that me...,UgzfBCWxKXiPG2ZJUFd4AaABAg,0,0,2022-01-17T20:03:46Z,1
...,...,...,...,...,...,...
596,I think that Riley looks more and more like Da...,UgxpHGabMoy6852IqYB4AaABAg,0,3,2019-08-18T16:03:31Z,3
597,I'm an early transition girl and honestly im r...,Ugyea2Qsk3xNRRLxBUd4AaABAg,0,10,2019-08-18T16:00:04Z,3
598,Holy Crap! The sibling analogy was brilliant. ...,UgycoRorOz5XHCLcXHp4AaABAg,0,1,2019-08-18T15:42:44Z,3
599,üíõüíôüíúüíö‚ù§ üí†üå∫‚ö™üå∫üí†\nThanks for the vid and all the in...,Ugw44qQi3y531-NsBuB4AaABAg,1,16,2019-08-18T15:39:44Z,3
600,Trans 101? Nice. \n\nI am super early. Also Ri...,UgyctEMNryT3sIErjHp4AaABAg,1,99,2019-08-18T15:34:59Z,3

In [23]:
ftm_df.to_csv("ftm_comments.csv", index=False)